//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNavigationDatabaseService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveDay
    {
        public long id { get; set; }
        public string day { get; set; }
        public System.TimeSpan start { get; set; }
        public System.TimeSpan end { get; set; }
        public string timezone { get; set; }
        public Nullable<long> EFAirspace_id { get; set; }
    
        public virtual Airspace tbl_Airspaces { get; set; }
    }
}
