//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNavigationDatabaseService.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class airnavdbEntities : DbContext
    {
        public airnavdbEntities()
            : base("name=airnavdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airport> tbl_Airports { get; set; }
        public virtual DbSet<tbl_Countries> tbl_Countries { get; set; }
        public virtual DbSet<tbl_Firs> tbl_Firs { get; set; }
        public virtual DbSet<tbl_Fixes> tbl_Fixes { get; set; }
        public virtual DbSet<tbl_Frequencies> tbl_Frequencies { get; set; }
        public virtual DbSet<tbl_Navaids> tbl_Navaids { get; set; }
        public virtual DbSet<tbl_Regions> tbl_Regions { get; set; }
        public virtual DbSet<tbl_Runways> tbl_Runways { get; set; }
        public virtual DbSet<tbl_Tiles> tbl_Tiles { get; set; }
        public virtual DbSet<tbl_links> tbl_links { get; set; }
    }
}
