//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNavigationDatabaseService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airspace
    {
        public long id { get; set; }
        public string name { get; set; }
        public string version { get; set; }
        public string category { get; set; }
        public long airspace_id { get; set; }
        public string country { get; set; }
        public long altLimit_top { get; set; }
        public string altLimit_top_unit { get; set; }
        public string altLimit_top_ref { get; set; }
        public long altLimit_bottom { get; set; }
        public string altLimit_bottom_unit { get; set; }
        public string altLimit_bottom_ref { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geometry { get; set; }
    }
}
