//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNavigationDatabaseService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fir
    {
        public int C_id { get; set; }
        public int id { get; set; }
        public string ident { get; set; }
        public string name { get; set; }
        public string position { get; set; }
        public string polygon { get; set; }
    }
}
