//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNavigationDatabaseService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frequency
    {
        public int id { get; set; }
        public int airport_ref { get; set; }
        public string airport_ident { get; set; }
        public string type { get; set; }
        public string description { get; set; }
        public double frequency_mhz { get; set; }
    
        public virtual Airport tbl_Airports { get; set; }
    }
}
