//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNavigationDatabaseService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navaid
    {
        public int C_id { get; set; }
        public int id { get; set; }
        public string filename { get; set; }
        public string ident { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public double frequency_khz { get; set; }
        public double latitude_deg { get; set; }
        public double longitude_deg { get; set; }
        public int elevation_ft { get; set; }
        public string iso_country { get; set; }
        public double dme_frequency_khz { get; set; }
        public double dme_channel { get; set; }
        public double dme_latitude_deg { get; set; }
        public double dme_longitude_deg { get; set; }
        public int dme_elevation_ft { get; set; }
        public double slaved_variation_deg { get; set; }
        public double magnetic_variation_deg { get; set; }
        public string usageType { get; set; }
        public string power { get; set; }
        public string associated_airport { get; set; }
        public int associated_airport_id { get; set; }
        public string continent { get; set; }
    }
}
