//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNavigationDatabaseService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Runways
    {
        public int C_id { get; set; }
        public int id { get; set; }
        public int airport_ref { get; set; }
        public string airport_ident { get; set; }
        public int length_ft { get; set; }
        public int width_ft { get; set; }
        public int lighted { get; set; }
        public int closed { get; set; }
        public string surface { get; set; }
        public string le_ident { get; set; }
        public double le_latitude_deg { get; set; }
        public double le_longitude_deg { get; set; }
        public int le_elevation_ft { get; set; }
        public double le_heading_degT { get; set; }
        public int le_displaced_threshold_ft { get; set; }
        public string he_ident { get; set; }
        public double he_latitude_deg { get; set; }
        public double he_longitude_deg { get; set; }
        public int he_elevation_ft { get; set; }
        public double he_heading_degT { get; set; }
        public int he_displaced_threshold_ft { get; set; }
    }
}
