//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNavigationDatabaseService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Continents
    {
        public long id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geometry { get; set; }
        public System.Data.Entity.Spatial.DbGeometry envelope { get; set; }
    }
}
