//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNavigationDatabaseService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Tiles
    {
        public int C_id { get; set; }
        public string name { get; set; }
        public string region { get; set; }
        public string type { get; set; }
        public string mbtileslink { get; set; }
        public string xmllink { get; set; }
        public string version { get; set; }
        public long startValidity { get; set; }
        public long endValidity { get; set; }
    }
}
