//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNavigationDatabaseService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Regions
    {
        public int C_id { get; set; }
        public int id { get; set; }
        public string code { get; set; }
        public string local_code { get; set; }
        public string name { get; set; }
        public string continent { get; set; }
        public string iso_country { get; set; }
        public string wikipedia_link { get; set; }
        public string keywords { get; set; }
    }
}
